<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "AccountExt".
 *
 * @property string $AccountID
 * @property string $Job
 * @property string $RecomID
 * @property integer $EmailStatus
 * @property string $aliasModel
 */
abstract class AccountExt extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'AccountExt';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'Job', 'RecomID', 'EmailStatus'], 'required'],
            [['AccountID', 'Job', 'RecomID'], 'string'],
            [['EmailStatus'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => 'Account ID',
            'Job' => 'Job',
            'RecomID' => 'Recom ID',
            'EmailStatus' => 'Email Status',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\AccountExtQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AccountExtQuery(get_called_class());
    }


}
