<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "AccountInfo".
 *
 * @property string $account
 * @property string $contact
 * @property string $name
 * @property string $email
 * @property string $ip
 * @property string $login_ip
 * @property integer $event_points
 * @property integer $cevent_points
 * @property integer $refresh_count
 * @property integer $ref_add_allow
 * @property string $referer
 * @property double $flamez_coins
 * @property string $forgot_pass_key
 * @property string $aliasModel
 */
abstract class AccountInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'AccountInfo';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['account', 'contact', 'name', 'email', 'ip', 'login_ip', 'referer', 'forgot_pass_key'], 'string'],
            [['event_points', 'cevent_points', 'refresh_count', 'ref_add_allow'], 'integer'],
            [['cevent_points', 'refresh_count', 'ref_add_allow'], 'required'],
            [['flamez_coins'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'account' => 'Account',
            'contact' => 'Contact',
            'name' => 'Name',
            'email' => 'Email',
            'ip' => 'Ip',
            'login_ip' => 'Login Ip',
            'event_points' => 'Event Points',
            'cevent_points' => 'Cevent Points',
            'refresh_count' => 'Refresh Count',
            'ref_add_allow' => 'Ref Add Allow',
            'referer' => 'Referer',
            'flamez_coins' => 'Flamez Coins',
            'forgot_pass_key' => 'Forgot Pass Key',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\AccountInfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AccountInfoQuery(get_called_class());
    }


}
