<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "AccountAuth".
 *
 * @property string $AccountID
 * @property string $AuthType
 * @property string $AuthDate
 * @property string $Result
 * @property string $aliasModel
 */
abstract class AccountAuth extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'AccountAuth';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'AuthType', 'AuthDate', 'Result'], 'required'],
            [['AccountID', 'AuthType', 'Result'], 'string'],
            [['AuthDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => Yii::t('models', 'Account ID'),
            'AuthType' => Yii::t('models', 'Auth Type'),
            'AuthDate' => Yii::t('models', 'Auth Date'),
            'Result' => Yii::t('models', 'Result'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\AccountAuthQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AccountAuthQuery(get_called_class());
    }


}
