<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "activity_log".
 *
 * @property string $id
 * @property integer $is_visible
 * @property string $account
 * @property string $character
 * @property integer $event
 * @property string $description
 * @property string $browser
 * @property string $operating_system
 * @property string $ip_address
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class ActivityLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'activity_log';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_visible', 'event'], 'integer'],
            [['account', 'character', 'description', 'browser', 'operating_system', 'ip_address'], 'string'],
            [['event'], 'required']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'is_visible' => Yii::t('models', 'Is Visible'),
            'account' => Yii::t('models', 'Account'),
            'character' => Yii::t('models', 'Character'),
            'event' => Yii::t('models', 'Event'),
            'description' => Yii::t('models', 'Description'),
            'browser' => Yii::t('models', 'Browser'),
            'operating_system' => Yii::t('models', 'Operating System'),
            'ip_address' => Yii::t('models', 'Ip Address'),
            'created_at' => Yii::t('models', 'Created At'),
            'updated_at' => Yii::t('models', 'Updated At'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ActivityLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ActivityLogQuery(get_called_class());
    }


}
