<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "activity_log".
 *
 * @property string $id
 * @property integer $is_visible
 * @property string $account
 * @property string $character
 * @property integer $event
 * @property string $description
 * @property string $data
 * @property string $browser
 * @property string $operating_system
 * @property string $ip_address
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class ActivityLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'activity_log';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_visible', 'event'], 'integer'],
            [['account', 'event'], 'required'],
            [['account', 'character', 'description', 'data', 'browser', 'operating_system', 'ip_address'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_visible' => 'Is Visible',
            'account' => 'Account',
            'character' => 'Character',
            'event' => 'Event',
            'description' => 'Description',
            'data' => 'Data',
            'browser' => 'Browser',
            'operating_system' => 'Operating System',
            'ip_address' => 'Ip Address',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ActivityLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ActivityLogQuery(get_called_class());
    }


}
