<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "Activation".
 *
 * @property string $act_id
 * @property string $account
 * @property string $aliasModel
 */
abstract class Activation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Activation';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['act_id', 'account'], 'required'],
            [['act_id', 'account'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'act_id' => 'Act ID',
            'account' => 'Account',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ActivationQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ActivationQuery(get_called_class());
    }


}
