<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "AdultCheck".
 *
 * @property string $Name
 * @property string $SCN
 * @property string $RegDate
 * @property string $aliasModel
 */
abstract class AdultCheck extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'AdultCheck';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Name', 'SCN'], 'required'],
            [['Name', 'SCN'], 'string'],
            [['RegDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'Name' => 'Name',
            'SCN' => 'Scn',
            'RegDate' => 'Reg Date',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\AdultCheckQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AdultCheckQuery(get_called_class());
    }


}
