<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "Answer".
 *
 * @property integer $QuestNo
 * @property integer $AnswerNo
 * @property string $Content
 * @property string $aliasModel
 */
abstract class Answer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Answer';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['QuestNo', 'AnswerNo', 'Content'], 'required'],
            [['QuestNo', 'AnswerNo'], 'integer'],
            [['Content'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'QuestNo' => Yii::t('models', 'Quest No'),
            'AnswerNo' => Yii::t('models', 'Answer No'),
            'Content' => Yii::t('models', 'Content'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\AnswerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AnswerQuery(get_called_class());
    }


}
