<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "AuthLog".
 *
 * @property integer $AuthLogID
 * @property string $AccountID
 * @property string $AuthType
 * @property string $AuthDate
 * @property string $Result
 * @property string $aliasModel
 */
abstract class AuthLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'AuthLog';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AuthLogID', 'AccountID', 'AuthType', 'AuthDate', 'Result'], 'required'],
            [['AuthLogID'], 'integer'],
            [['AccountID', 'AuthType', 'Result'], 'string'],
            [['AuthDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AuthLogID' => 'Auth Log ID',
            'AccountID' => 'Account ID',
            'AuthType' => 'Auth Type',
            'AuthDate' => 'Auth Date',
            'Result' => 'Result',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\AuthLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\AuthLogQuery(get_called_class());
    }


}
