<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "Banlist".
 *
 * @property string $c_id
 * @property string $account
 * @property string $tim
 * @property string $aliasModel
 */
abstract class Banlist extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Banlist';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['c_id', 'account', 'tim'], 'required'],
            [['c_id', 'account'], 'string'],
            [['tim'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'c_id' => 'C ID',
            'account' => 'Account',
            'tim' => 'Tim',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BanlistQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BanlistQuery(get_called_class());
    }


}
