<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "BetaPcbang".
 *
 * @property string $AccountID
 * @property string $PcbangCode
 * @property string $PcbangName
 * @property string $Owner
 * @property string $Scn
 * @property string $OpenDate
 * @property string $PcbangAddress
 * @property string $PcbangZipcode
 * @property string $OwnerAddress
 * @property string $OwnerZipcode
 * @property string $Uptae
 * @property string $Upzong
 * @property string $Semuser
 * @property string $AccountIDStatus
 * @property string $RequestDate
 * @property string $Result
 * @property string $ResultDesc
 * @property string $ResultUser
 * @property string $ResultDate
 * @property integer $ResultNo
 * @property string $ResultType
 * @property string $Tel
 * @property string $aliasModel
 */
abstract class BetaPcbang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'BetaPcbang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'AccountIDStatus', 'RequestDate', 'Result', 'ResultNo', 'ResultType'], 'required'],
            [['AccountID', 'PcbangCode', 'PcbangName', 'Owner', 'Scn', 'OpenDate', 'PcbangAddress', 'PcbangZipcode', 'OwnerAddress', 'OwnerZipcode', 'Uptae', 'Upzong', 'Semuser', 'AccountIDStatus', 'Result', 'ResultDesc', 'ResultUser', 'ResultType', 'Tel'], 'string'],
            [['RequestDate', 'ResultDate'], 'safe'],
            [['ResultNo'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => Yii::t('models', 'Account ID'),
            'PcbangCode' => Yii::t('models', 'Pcbang Code'),
            'PcbangName' => Yii::t('models', 'Pcbang Name'),
            'Owner' => Yii::t('models', 'Owner'),
            'Scn' => Yii::t('models', 'Scn'),
            'OpenDate' => Yii::t('models', 'Open Date'),
            'PcbangAddress' => Yii::t('models', 'Pcbang Address'),
            'PcbangZipcode' => Yii::t('models', 'Pcbang Zipcode'),
            'OwnerAddress' => Yii::t('models', 'Owner Address'),
            'OwnerZipcode' => Yii::t('models', 'Owner Zipcode'),
            'Uptae' => Yii::t('models', 'Uptae'),
            'Upzong' => Yii::t('models', 'Upzong'),
            'Semuser' => Yii::t('models', 'Semuser'),
            'AccountIDStatus' => Yii::t('models', 'Account Idstatus'),
            'RequestDate' => Yii::t('models', 'Request Date'),
            'Result' => Yii::t('models', 'Result'),
            'ResultDesc' => Yii::t('models', 'Result Desc'),
            'ResultUser' => Yii::t('models', 'Result User'),
            'ResultDate' => Yii::t('models', 'Result Date'),
            'ResultNo' => Yii::t('models', 'Result No'),
            'ResultType' => Yii::t('models', 'Result Type'),
            'Tel' => Yii::t('models', 'Tel'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BetaPcbangQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BetaPcbangQuery(get_called_class());
    }


}
