<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "BetaPcbang".
 *
 * @property string $AccountID
 * @property string $PcbangCode
 * @property string $PcbangName
 * @property string $Owner
 * @property string $Scn
 * @property string $OpenDate
 * @property string $PcbangAddress
 * @property string $PcbangZipcode
 * @property string $OwnerAddress
 * @property string $OwnerZipcode
 * @property string $Uptae
 * @property string $Upzong
 * @property string $Semuser
 * @property string $AccountIDStatus
 * @property string $RequestDate
 * @property string $Result
 * @property string $ResultDesc
 * @property string $ResultUser
 * @property string $ResultDate
 * @property integer $ResultNo
 * @property string $ResultType
 * @property string $Tel
 * @property string $aliasModel
 */
abstract class BetaPcbang extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'BetaPcbang';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'AccountIDStatus', 'RequestDate', 'Result', 'ResultNo', 'ResultType'], 'required'],
            [['AccountID', 'PcbangCode', 'PcbangName', 'Owner', 'Scn', 'OpenDate', 'PcbangAddress', 'PcbangZipcode', 'OwnerAddress', 'OwnerZipcode', 'Uptae', 'Upzong', 'Semuser', 'AccountIDStatus', 'Result', 'ResultDesc', 'ResultUser', 'ResultType', 'Tel'], 'string'],
            [['RequestDate', 'ResultDate'], 'safe'],
            [['ResultNo'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => 'Account ID',
            'PcbangCode' => 'Pcbang Code',
            'PcbangName' => 'Pcbang Name',
            'Owner' => 'Owner',
            'Scn' => 'Scn',
            'OpenDate' => 'Open Date',
            'PcbangAddress' => 'Pcbang Address',
            'PcbangZipcode' => 'Pcbang Zipcode',
            'OwnerAddress' => 'Owner Address',
            'OwnerZipcode' => 'Owner Zipcode',
            'Uptae' => 'Uptae',
            'Upzong' => 'Upzong',
            'Semuser' => 'Semuser',
            'AccountIDStatus' => 'Account Idstatus',
            'RequestDate' => 'Request Date',
            'Result' => 'Result',
            'ResultDesc' => 'Result Desc',
            'ResultUser' => 'Result User',
            'ResultDate' => 'Result Date',
            'ResultNo' => 'Result No',
            'ResultType' => 'Result Type',
            'Tel' => 'Tel',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BetaPcbangQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BetaPcbangQuery(get_called_class());
    }


}
