<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "BetaTester3".
 *
 * @property integer $BetaID
 * @property integer $BetaRandNum
 * @property string $AccountID
 * @property string $Scn
 * @property string $ZipCode
 * @property string $Region
 * @property string $Age
 * @property integer $Sex
 * @property string $Result
 * @property integer $BetaNum
 * @property string $aliasModel
 */
abstract class BetaTester3 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'BetaTester3';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['BetaID', 'AccountID'], 'required'],
            [['BetaID', 'BetaRandNum', 'Sex', 'BetaNum'], 'integer'],
            [['AccountID', 'Scn', 'ZipCode', 'Region', 'Age', 'Result'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'BetaID' => 'Beta ID',
            'BetaRandNum' => 'Beta Rand Num',
            'AccountID' => 'Account ID',
            'Scn' => 'Scn',
            'ZipCode' => 'Zip Code',
            'Region' => 'Region',
            'Age' => 'Age',
            'Sex' => 'Sex',
            'Result' => 'Result',
            'BetaNum' => 'Beta Num',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BetaTester3Query the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BetaTester3Query(get_called_class());
    }


}
