<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "BetaArgee".
 *
 * @property string $AccountID
 * @property integer $AgreeStatus
 * @property string $aliasModel
 */
abstract class BetaArgee extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'BetaArgee';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'AgreeStatus'], 'required'],
            [['AccountID'], 'string'],
            [['AgreeStatus'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => Yii::t('models', 'Account ID'),
            'AgreeStatus' => Yii::t('models', 'Agree Status'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BetaArgeeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BetaArgeeQuery(get_called_class());
    }


}
