<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "BetaTester4".
 *
 * @property integer $BetaID
 * @property integer $BetaRandNum
 * @property string $AccountID
 * @property string $Scn
 * @property string $ZipCode
 * @property string $Region
 * @property string $Age
 * @property integer $Sex
 * @property string $Result
 * @property integer $BetaNum
 * @property string $aliasModel
 */
abstract class BetaTester4 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'BetaTester4';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['BetaID', 'AccountID'], 'required'],
            [['BetaID', 'BetaRandNum', 'Sex', 'BetaNum'], 'integer'],
            [['AccountID', 'Scn', 'ZipCode', 'Region', 'Age', 'Result'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'BetaID' => Yii::t('models', 'Beta ID'),
            'BetaRandNum' => Yii::t('models', 'Beta Rand Num'),
            'AccountID' => Yii::t('models', 'Account ID'),
            'Scn' => Yii::t('models', 'Scn'),
            'ZipCode' => Yii::t('models', 'Zip Code'),
            'Region' => Yii::t('models', 'Region'),
            'Age' => Yii::t('models', 'Age'),
            'Sex' => Yii::t('models', 'Sex'),
            'Result' => Yii::t('models', 'Result'),
            'BetaNum' => Yii::t('models', 'Beta Num'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BetaTester4Query the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BetaTester4Query(get_called_class());
    }


}
