<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "BetaPcbangIP".
 *
 * @property string $AccountID
 * @property string $IP
 * @property string $Result
 * @property string $aliasModel
 */
abstract class BetaPcbangIP extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'BetaPcbangIP';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'IP', 'Result'], 'required'],
            [['AccountID', 'IP', 'Result'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => 'Account ID',
            'IP' => 'Ip',
            'Result' => 'Result',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BetaPcbangIPQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BetaPcbangIPQuery(get_called_class());
    }


}
