<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "bundle_item".
 *
 * @property integer $id
 * @property integer $is_deleted
 * @property integer $bundle_id
 * @property integer $item_id
 * @property integer $quantity
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\Bundle $bundle
 * @property \common\models\Item $item
 * @property string $aliasModel
 */
abstract class BundleItem extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bundle_item';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_deleted', 'bundle_id', 'item_id', 'quantity'], 'integer'],
            [['bundle_id', 'item_id'], 'required'],
            [['meta'], 'string'],
            [['bundle_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Bundle::className(), 'targetAttribute' => ['bundle_id' => 'id']],
            [['item_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Item::className(), 'targetAttribute' => ['item_id' => 'item_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_deleted' => 'Is Deleted',
            'bundle_id' => 'Bundle ID',
            'item_id' => 'Item ID',
            'quantity' => 'Quantity',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBundle()
    {
        return $this->hasOne(\common\models\Bundle::className(), ['id' => 'bundle_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(\common\models\Item::className(), ['item_id' => 'item_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BundleItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BundleItemQuery(get_called_class());
    }


}
