<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "bundle".
 *
 * @property integer $id
 * @property integer $is_deleted
 * @property string $name
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\BundleItem[] $bundleItems
 * @property \common\models\EshopItem[] $eshopItems
 * @property string $aliasModel
 */
abstract class Bundle extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bundle';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_deleted'], 'integer'],
            [['name'], 'required'],
            [['name', 'meta'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_deleted' => 'Is Deleted',
            'name' => 'Name',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBundleItems()
    {
        return $this->hasMany(\common\models\BundleItem::className(), ['bundle_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEshopItems()
    {
        return $this->hasMany(\common\models\EshopItem::className(), ['bundle_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BundleQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BundleQuery(get_called_class());
    }


}
