<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "buy_uniq_code".
 *
 * @property string $transaction_id
 * @property string $item_code
 * @property string $unique_code
 * @property string $aliasModel
 */
abstract class BuyUniqCode extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'buy_uniq_code';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['transaction_id', 'item_code', 'unique_code'], 'required'],
            [['transaction_id', 'item_code', 'unique_code'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'transaction_id' => 'Transaction ID',
            'item_code' => 'Item Code',
            'unique_code' => 'Unique Code',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\BuyUniqCodeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BuyUniqCodeQuery(get_called_class());
    }


}
