<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "cdg_mondrops".
 *
 * @property integer $monsterid
 * @property integer $itemcode
 * @property string $dropcount
 * @property string $monstername
 * @property string $aliasModel
 */
abstract class CdgMondrops extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cdg_mondrops';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['monsterid', 'itemcode', 'dropcount'], 'integer'],
            [['monstername'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'monsterid' => 'Monsterid',
            'itemcode' => 'Itemcode',
            'dropcount' => 'Dropcount',
            'monstername' => 'Monstername',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CdgMondropsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CdgMondropsQuery(get_called_class());
    }


}
