<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "charloginlog".
 *
 * @property string $c_id
 * @property integer $rb
 * @property integer $lvl
 * @property string $datetime
 * @property string $class
 * @property integer $Nation
 * @property string $aliasModel
 */
abstract class Charloginlog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'charloginlog';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['c_id'], 'required'],
            [['c_id', 'datetime', 'class'], 'string'],
            [['rb', 'lvl', 'Nation'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'c_id' => 'C ID',
            'rb' => 'Rb',
            'lvl' => 'Lvl',
            'datetime' => 'Datetime',
            'class' => 'Class',
            'Nation' => 'Nation',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CharloginlogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CharloginlogQuery(get_called_class());
    }


}
