<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "character_spree".
 *
 * @property integer $id
 * @property integer $is_deleted
 * @property string $character
 * @property integer $type
 * @property integer $count
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class CharacterSpree extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'character_spree';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_deleted', 'type', 'count'], 'integer'],
            [['character'], 'required'],
            [['character', 'meta'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_deleted' => 'Is Deleted',
            'character' => 'Character',
            'type' => 'Type',
            'count' => 'Count',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CharacterSpreeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CharacterSpreeQuery(get_called_class());
    }


}
