<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "Charac0ex".
 *
 * @property string $c_id
 * @property integer $str
 * @property integer $inte
 * @property integer $dex
 * @property integer $hp
 * @property integer $mp
 * @property integer $points
 * @property integer $rstr
 * @property integer $rinte
 * @property integer $rdex
 * @property integer $rhp
 * @property integer $rmp
 * @property integer $rpoints
 * @property integer $level
 * @property string $aliasModel
 */
abstract class Charac0ex extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Charac0ex';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['c_id'], 'required'],
            [['c_id'], 'string'],
            [['str', 'inte', 'dex', 'hp', 'mp', 'points', 'rstr', 'rinte', 'rdex', 'rhp', 'rmp', 'rpoints', 'level'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'c_id' => Yii::t('models', 'C ID'),
            'str' => Yii::t('models', 'Str'),
            'inte' => Yii::t('models', 'Inte'),
            'dex' => Yii::t('models', 'Dex'),
            'hp' => Yii::t('models', 'Hp'),
            'mp' => Yii::t('models', 'Mp'),
            'points' => Yii::t('models', 'Points'),
            'rstr' => Yii::t('models', 'Rstr'),
            'rinte' => Yii::t('models', 'Rinte'),
            'rdex' => Yii::t('models', 'Rdex'),
            'rhp' => Yii::t('models', 'Rhp'),
            'rmp' => Yii::t('models', 'Rmp'),
            'rpoints' => Yii::t('models', 'Rpoints'),
            'level' => Yii::t('models', 'Level'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\Charac0exQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\Charac0exQuery(get_called_class());
    }


}
