<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "CharInfo".
 *
 * @property string $AccountID
 * @property string $ServerIdx
 * @property string $CharName
 * @property string $Class
 * @property string $Nation
 * @property string $default
 * @property string $aliasModel
 */
abstract class CharInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'CharInfo';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'ServerIdx', 'CharName', 'Class', 'Nation', 'default'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => 'Account ID',
            'ServerIdx' => 'Server Idx',
            'CharName' => 'Char Name',
            'Class' => 'Class',
            'Nation' => 'Nation',
            'default' => 'Default',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CharInfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CharInfoQuery(get_called_class());
    }


}
