<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ChristmasGiftInfo".
 *
 * @property integer $gift_code
 * @property string $gift_name
 * @property string $gift_item_code
 * @property integer $gift_points
 * @property integer $gift_took
 * @property string $gift_taken
 * @property string $aliasModel
 */
abstract class ChristmasGiftInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ChristmasGiftInfo';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['gift_code', 'gift_name', 'gift_item_code', 'gift_points', 'gift_took', 'gift_taken'], 'required'],
            [['gift_code', 'gift_points', 'gift_took'], 'integer'],
            [['gift_name', 'gift_item_code', 'gift_taken'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'gift_code' => Yii::t('models', 'Gift Code'),
            'gift_name' => Yii::t('models', 'Gift Name'),
            'gift_item_code' => Yii::t('models', 'Gift Item Code'),
            'gift_points' => Yii::t('models', 'Gift Points'),
            'gift_took' => Yii::t('models', 'Gift Took'),
            'gift_taken' => Yii::t('models', 'Gift Taken'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ChristmasGiftInfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ChristmasGiftInfoQuery(get_called_class());
    }


}
