<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ClanInfo".
 *
 * @property integer $ClanID
 * @property string $ServerID
 * @property string $ClanName
 * @property string $MasterName
 * @property string $Nation
 * @property string $MarkID
 * @property string $CDate
 * @property string $DDate
 * @property string $ClanPasswd
 * @property string $ClanRank
 * @property string $ClanStatus
 * @property string $StorageID
 * @property integer $AgitID
 * @property integer $WinCount
 * @property integer $LoseCount
 * @property string $aliasModel
 */
abstract class ClanInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ClanInfo';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ClanID'], 'required'],
            [['ClanID', 'AgitID', 'WinCount', 'LoseCount'], 'integer'],
            [['ServerID', 'ClanName', 'MasterName', 'Nation', 'MarkID', 'ClanPasswd', 'ClanRank', 'ClanStatus', 'StorageID'], 'string'],
            [['CDate', 'DDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ClanID' => 'Clan ID',
            'ServerID' => 'Server ID',
            'ClanName' => 'Clan Name',
            'MasterName' => 'Master Name',
            'Nation' => 'Nation',
            'MarkID' => 'Mark ID',
            'CDate' => 'Cdate',
            'DDate' => 'Ddate',
            'ClanPasswd' => 'Clan Passwd',
            'ClanRank' => 'Clan Rank',
            'ClanStatus' => 'Clan Status',
            'StorageID' => 'Storage ID',
            'AgitID' => 'Agit ID',
            'WinCount' => 'Win Count',
            'LoseCount' => 'Lose Count',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ClanInfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ClanInfoQuery(get_called_class());
    }


}
