<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "connect_old_account_request".
 *
 * @property integer $id
 * @property integer $connect_old_account_id
 * @property string $token
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\ConnectOldAccount $connectOldAccount
 * @property string $aliasModel
 */
abstract class ConnectOldAccountRequest extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'connect_old_account_request';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['connect_old_account_id', 'token'], 'required'],
            [['connect_old_account_id'], 'integer'],
            [['token', 'meta'], 'string'],
            [['connect_old_account_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ConnectOldAccount::className(), 'targetAttribute' => ['connect_old_account_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'connect_old_account_id' => 'Connect Old Account ID',
            'token' => 'Token',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConnectOldAccount()
    {
        return $this->hasOne(\common\models\ConnectOldAccount::className(), ['id' => 'connect_old_account_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ConnectOldAccountRequestQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ConnectOldAccountRequestQuery(get_called_class());
    }


}
