<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "connect_old_account".
 *
 * @property integer $id
 * @property string $current_account
 * @property string $old_account
 * @property integer $coin_given
 * @property integer $status
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\ConnectOldAccountRequest[] $connectOldAccountRequests
 * @property string $aliasModel
 */
abstract class ConnectOldAccount extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'connect_old_account';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['current_account', 'old_account'], 'required'],
            [['current_account', 'old_account', 'meta'], 'string'],
            [['coin_given', 'status'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'current_account' => 'Current Account',
            'old_account' => 'Old Account',
            'coin_given' => 'Coin Given',
            'status' => 'Status',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConnectOldAccountRequests()
    {
        return $this->hasMany(\common\models\ConnectOldAccountRequest::className(), ['connect_old_account_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ConnectOldAccountQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ConnectOldAccountQuery(get_called_class());
    }


}
