<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "Count".
 *
 * @property integer $count
 * @property string $aliasModel
 */
abstract class Count extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Count';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['count'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'count' => 'Count',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CountQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CountQuery(get_called_class());
    }


}
