<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "coupon_table".
 *
 * @property integer $id
 * @property string $coupon_code
 * @property integer $discount
 * @property string $character
 * @property integer $min_amt
 * @property string $gift_time
 * @property integer $flag
 * @property string $aliasModel
 */
abstract class CouponTable extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'coupon_table';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'coupon_code', 'discount', 'character', 'min_amt', 'gift_time'], 'required'],
            [['id', 'discount', 'min_amt', 'flag'], 'integer'],
            [['coupon_code', 'character', 'gift_time'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'coupon_code' => Yii::t('models', 'Coupon Code'),
            'discount' => Yii::t('models', 'Discount'),
            'character' => Yii::t('models', 'Character'),
            'min_amt' => Yii::t('models', 'Min Amt'),
            'gift_time' => Yii::t('models', 'Gift Time'),
            'flag' => Yii::t('models', 'Flag'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CouponTableQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CouponTableQuery(get_called_class());
    }


}
