<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "CurrentGift".
 *
 * @property string $account
 * @property integer $current_gift
 * @property string $aliasModel
 */
abstract class CurrentGift extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'CurrentGift';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['account', 'current_gift'], 'required'],
            [['account'], 'string'],
            [['current_gift'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'account' => 'Account',
            'current_gift' => 'Current Gift',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\CurrentGiftQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\CurrentGiftQuery(get_called_class());
    }


}
