<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "daily_quest".
 *
 * @property integer $id
 * @property integer $is_deleted
 * @property string $character
 * @property string $taken_at
 * @property string $submitted_at
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class DailyQuest extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'daily_quest';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_deleted'], 'integer'],
            [['character'], 'required'],
            [['character', 'meta'], 'string'],
            [['taken_at', 'submitted_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_deleted' => 'Is Deleted',
            'character' => 'Character',
            'taken_at' => 'Taken At',
            'submitted_at' => 'Submitted At',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\DailyQuestQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\DailyQuestQuery(get_called_class());
    }


}
