<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "delivery_table".
 *
 * @property string $transaction_id
 * @property string $account_name
 * @property string $char_name
 * @property string $item_ids
 * @property string $delivery_time
 * @property string $credits_used
 * @property string $ip_address
 * @property string $coupon_code
 * @property string $aliasModel
 */
abstract class DeliveryTable extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'delivery_table';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['transaction_id', 'account_name', 'char_name', 'item_ids', 'delivery_time', 'credits_used', 'ip_address'], 'required'],
            [['transaction_id', 'account_name', 'char_name', 'item_ids', 'delivery_time', 'ip_address', 'coupon_code'], 'string'],
            [['credits_used'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'transaction_id' => 'Transaction ID',
            'account_name' => 'Account Name',
            'char_name' => 'Char Name',
            'item_ids' => 'Item Ids',
            'delivery_time' => 'Delivery Time',
            'credits_used' => 'Credits Used',
            'ip_address' => 'Ip Address',
            'coupon_code' => 'Coupon Code',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\DeliveryTableQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\DeliveryTableQuery(get_called_class());
    }


}
