<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "DenyChar".
 *
 * @property string $DenyCharID
 * @property string $aliasModel
 */
abstract class DenyChar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'DenyChar';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['DenyCharID'], 'required'],
            [['DenyCharID'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'DenyCharID' => Yii::t('models', 'Deny Char ID'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\DenyCharQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\DenyCharQuery(get_called_class());
    }


}
