<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "dtproperties".
 *
 * @property integer $id
 * @property integer $objectid
 * @property string $property
 * @property string $value
 * @property string $uvalue
 * @property resource $lvalue
 * @property integer $version
 * @property string $aliasModel
 */
abstract class Dtproperties extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'dtproperties';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['objectid', 'version'], 'integer'],
            [['property'], 'required'],
            [['property', 'value', 'uvalue', 'lvalue'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'objectid' => 'Objectid',
            'property' => 'Property',
            'value' => 'Value',
            'uvalue' => 'Uvalue',
            'lvalue' => 'Lvalue',
            'version' => 'Version',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\DtpropertiesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\DtpropertiesQuery(get_called_class());
    }


}
