<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "eshop_item".
 *
 * @property integer $id
 * @property integer $is_deleted
 * @property integer $item_id
 * @property string $display_name
 * @property string $description
 * @property string $image_url
 * @property integer $category
 * @property double $coin
 * @property double $cash
 * @property double $credit
 * @property string $meta
 * @property integer $bundle_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\EshopCoupon[] $eshopCoupons
 * @property \common\models\Bundle $bundle
 * @property \common\models\Item $item
 * @property \common\models\EshopOrderItem[] $eshopOrderItems
 * @property \common\models\Gift[] $gifts
 * @property string $aliasModel
 */
abstract class EshopItem extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'eshop_item';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_deleted', 'item_id', 'category', 'bundle_id'], 'integer'],
            [['item_id'], 'required'],
            [['display_name', 'description', 'image_url', 'meta'], 'string'],
            [['coin', 'cash', 'credit'], 'number'],
            [['bundle_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Bundle::className(), 'targetAttribute' => ['bundle_id' => 'id']],
            [['item_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Item::className(), 'targetAttribute' => ['item_id' => 'item_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_deleted' => 'Is Deleted',
            'item_id' => 'Item ID',
            'display_name' => 'Display Name',
            'description' => 'Description',
            'image_url' => 'Image Url',
            'category' => 'Category',
            'coin' => 'Coin',
            'cash' => 'Cash',
            'credit' => 'Credit',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'bundle_id' => 'Bundle ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEshopCoupons()
    {
        return $this->hasMany(\common\models\EshopCoupon::className(), ['eshop_item_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBundle()
    {
        return $this->hasOne(\common\models\Bundle::className(), ['id' => 'bundle_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(\common\models\Item::className(), ['item_id' => 'item_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEshopOrderItems()
    {
        return $this->hasMany(\common\models\EshopOrderItem::className(), ['eshop_item_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGifts()
    {
        return $this->hasMany(\common\models\Gift::className(), ['eshop_item_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\EshopItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\EshopItemQuery(get_called_class());
    }


}
