<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "eshop_order_item".
 *
 * @property integer $id
 * @property integer $is_deleted
 * @property integer $eshop_item_id
 * @property integer $eshop_order_id
 * @property integer $quantity
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\EshopItem $eshopItem
 * @property \common\models\EshopOrder $eshopOrder
 * @property string $aliasModel
 */
abstract class EshopOrderItem extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'eshop_order_item';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_deleted', 'eshop_item_id', 'eshop_order_id', 'quantity'], 'integer'],
            [['eshop_item_id', 'eshop_order_id'], 'required'],
            [['meta'], 'string'],
            [['eshop_item_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\EshopItem::className(), 'targetAttribute' => ['eshop_item_id' => 'id']],
            [['eshop_order_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\EshopOrder::className(), 'targetAttribute' => ['eshop_order_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_deleted' => 'Is Deleted',
            'eshop_item_id' => 'Eshop Item ID',
            'eshop_order_id' => 'Eshop Order ID',
            'quantity' => 'Quantity',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEshopItem()
    {
        return $this->hasOne(\common\models\EshopItem::className(), ['id' => 'eshop_item_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEshopOrder()
    {
        return $this->hasOne(\common\models\EshopOrder::className(), ['id' => 'eshop_order_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\EshopOrderItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\EshopOrderItemQuery(get_called_class());
    }


}
