<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "event_points".
 *
 * @property integer $id
 * @property string $account
 * @property integer $type
 * @property integer $points
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 * @property string $aliasModel
 */
abstract class EventPoints extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'event_points';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['account', 'type'], 'required'],
            [['account', 'meta'], 'string'],
            [['type', 'points'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'account' => 'Account',
            'type' => 'Type',
            'points' => 'Points',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\EventPointsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\EventPointsQuery(get_called_class());
    }


}
