<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "GameLoginLog".
 *
 * @property integer $LoginIdx
 * @property string $AccountID
 * @property string $LoginIP
 * @property string $LoginDate
 * @property string $PayMode
 * @property string $aliasModel
 */
abstract class GameLoginLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'GameLoginLog';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['LoginIdx', 'AccountID', 'LoginIP', 'LoginDate', 'PayMode'], 'required'],
            [['LoginIdx'], 'integer'],
            [['AccountID', 'LoginIP', 'PayMode'], 'string'],
            [['LoginDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'LoginIdx' => 'Login Idx',
            'AccountID' => 'Account ID',
            'LoginIP' => 'Login Ip',
            'LoginDate' => 'Login Date',
            'PayMode' => 'Pay Mode',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\GameLoginLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\GameLoginLogQuery(get_called_class());
    }


}
