<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "GameBroadcast".
 *
 * @property integer $GameBroadcastID
 * @property string $AccountID
 * @property string $RequestDate
 * @property string $Job
 * @property string $Motive
 * @property string $Intro
 * @property string $FilePath
 * @property string $aliasModel
 */
abstract class GameBroadcast extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'GameBroadcast';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['GameBroadcastID', 'AccountID', 'RequestDate', 'Job', 'Motive', 'Intro', 'FilePath'], 'required'],
            [['GameBroadcastID'], 'integer'],
            [['AccountID', 'Job', 'Motive', 'Intro', 'FilePath'], 'string'],
            [['RequestDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'GameBroadcastID' => Yii::t('models', 'Game Broadcast ID'),
            'AccountID' => Yii::t('models', 'Account ID'),
            'RequestDate' => Yii::t('models', 'Request Date'),
            'Job' => Yii::t('models', 'Job'),
            'Motive' => Yii::t('models', 'Motive'),
            'Intro' => Yii::t('models', 'Intro'),
            'FilePath' => Yii::t('models', 'File Path'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\GameBroadcastQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\GameBroadcastQuery(get_called_class());
    }


}
