<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "GameServer".
 *
 * @property integer $ServerIdx
 * @property string $ServerName
 * @property integer $CntRegist
 * @property string $aliasModel
 */
abstract class GameServer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'GameServer';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['ServerIdx', 'ServerName', 'CntRegist'], 'required'],
            [['ServerIdx', 'CntRegist'], 'integer'],
            [['ServerName'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'ServerIdx' => 'Server Idx',
            'ServerName' => 'Server Name',
            'CntRegist' => 'Cnt Regist',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\GameServerQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\GameServerQuery(get_called_class());
    }


}
