<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "gift".
 *
 * @property integer $id
 * @property integer $is_deleted
 * @property string $character
 * @property integer $type
 * @property integer $eshop_item_id
 * @property integer $coins
 * @property integer $cash
 * @property integer $eshop_coupon_id
 * @property integer $is_taken
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\EshopCoupon $eshopCoupon
 * @property \common\models\EshopItem $eshopItem
 * @property string $aliasModel
 */
abstract class Gift extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gift';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['is_deleted', 'type', 'eshop_item_id', 'coins', 'cash', 'eshop_coupon_id', 'is_taken'], 'integer'],
            [['character'], 'required'],
            [['character', 'meta'], 'string'],
            [['eshop_coupon_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\EshopCoupon::className(), 'targetAttribute' => ['eshop_coupon_id' => 'id']],
            [['eshop_item_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\EshopItem::className(), 'targetAttribute' => ['eshop_item_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_deleted' => 'Is Deleted',
            'character' => 'Character',
            'type' => 'Type',
            'eshop_item_id' => 'Eshop Item ID',
            'coins' => 'Coins',
            'cash' => 'Cash',
            'eshop_coupon_id' => 'Eshop Coupon ID',
            'is_taken' => 'Is Taken',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEshopCoupon()
    {
        return $this->hasOne(\common\models\EshopCoupon::className(), ['id' => 'eshop_coupon_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEshopItem()
    {
        return $this->hasOne(\common\models\EshopItem::className(), ['id' => 'eshop_item_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\GiftQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\GiftQuery(get_called_class());
    }


}
