<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "GiftInfo".
 *
 * @property string $account
 * @property string $gift
 * @property string $time
 * @property string $aliasModel
 */
abstract class GiftInfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'GiftInfo';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['account', 'gift'], 'string'],
            [['time'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'account' => 'Account',
            'gift' => 'Gift',
            'time' => 'Time',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\GiftInfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\GiftInfoQuery(get_called_class());
    }


}
