<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "InnerAccount".
 *
 * @property string $AccountID
 * @property string $Desc
 * @property string $CreateDate
 * @property string $Creater
 * @property string $aliasModel
 */
abstract class InnerAccount extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'InnerAccount';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'Desc', 'CreateDate', 'Creater'], 'required'],
            [['AccountID', 'Desc', 'Creater'], 'string'],
            [['CreateDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => 'Account ID',
            'Desc' => 'Desc',
            'CreateDate' => 'Create Date',
            'Creater' => 'Creater',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\InnerAccountQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\InnerAccountQuery(get_called_class());
    }


}
