<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "item_table".
 *
 * @property string $item_id
 * @property string $item_name
 * @property string $item_category
 * @property string $item_code
 * @property string $items_count
 * @property string $item_pic
 * @property string $buy_credits
 * @property string $rent_credits
 * @property string $aliasModel
 */
abstract class ItemTable extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_table';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['item_id', 'item_name', 'item_category', 'item_code', 'items_count', 'item_pic', 'buy_credits'], 'required'],
            [['item_id', 'items_count', 'buy_credits', 'rent_credits'], 'integer'],
            [['item_name', 'item_category', 'item_code', 'item_pic'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'item_id' => 'Item ID',
            'item_name' => 'Item Name',
            'item_category' => 'Item Category',
            'item_code' => 'Item Code',
            'items_count' => 'Items Count',
            'item_pic' => 'Item Pic',
            'buy_credits' => 'Buy Credits',
            'rent_credits' => 'Rent Credits',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ItemTableQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ItemTableQuery(get_called_class());
    }


}
