<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "LoginLog".
 *
 * @property string $SCN
 * @property string $LoginDate
 * @property string $aliasModel
 */
abstract class LoginLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'LoginLog';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['SCN', 'LoginDate'], 'required'],
            [['SCN'], 'string'],
            [['LoginDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'SCN' => Yii::t('models', 'Scn'),
            'LoginDate' => Yii::t('models', 'Login Date'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\LoginLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\LoginLogQuery(get_called_class());
    }


}
