<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "LotteryTicket".
 *
 * @property string $LotteryTicketID
 * @property string $IsUsed
 * @property string $TicketNo
 * @property string $aliasModel
 */
abstract class LotteryTicket extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'LotteryTicket';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['LotteryTicketID', 'IsUsed', 'TicketNo'], 'required'],
            [['LotteryTicketID'], 'integer'],
            [['IsUsed', 'TicketNo'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'LotteryTicketID' => 'Lottery Ticket ID',
            'IsUsed' => 'Is Used',
            'TicketNo' => 'Ticket No',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\LotteryTicketQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\LotteryTicketQuery(get_called_class());
    }


}
