<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "LottoEvent".
 *
 * @property integer $LottoEventID
 * @property string $EventName
 * @property string $aliasModel
 */
abstract class LottoEvent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'LottoEvent';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['LottoEventID', 'EventName'], 'required'],
            [['LottoEventID'], 'integer'],
            [['EventName'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'LottoEventID' => 'Lotto Event ID',
            'EventName' => 'Event Name',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\LottoEventQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\LottoEventQuery(get_called_class());
    }


}
