<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "map_monster".
 *
 * @property integer $id
 * @property integer $map_id
 * @property integer $monster_id
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\Map $map
 * @property \common\models\Monster $monster
 * @property string $aliasModel
 */
abstract class MapMonster extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'map_monster';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['map_id', 'monster_id'], 'required'],
            [['map_id', 'monster_id'], 'integer'],
            [['meta'], 'string'],
            [['map_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Map::className(), 'targetAttribute' => ['map_id' => 'map_id']],
            [['monster_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Monster::className(), 'targetAttribute' => ['monster_id' => 'monster_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'map_id' => 'Map ID',
            'monster_id' => 'Monster ID',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMap()
    {
        return $this->hasOne(\common\models\Map::className(), ['map_id' => 'map_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMonster()
    {
        return $this->hasOne(\common\models\Monster::className(), ['monster_id' => 'monster_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\MapMonsterQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\MapMonsterQuery(get_called_class());
    }


}
