<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "monster_item".
 *
 * @property integer $id
 * @property integer $monster_id
 * @property integer $item_id
 * @property integer $drop_rate
 * @property string $meta
 * @property string $created_at
 * @property string $updated_at
 *
 * @property \common\models\Item $item
 * @property \common\models\Monster $monster
 * @property string $aliasModel
 */
abstract class MonsterItem extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'monster_item';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['monster_id', 'item_id'], 'required'],
            [['monster_id', 'item_id', 'drop_rate'], 'integer'],
            [['meta'], 'string'],
            [['item_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Item::className(), 'targetAttribute' => ['item_id' => 'item_id']],
            [['monster_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Monster::className(), 'targetAttribute' => ['monster_id' => 'monster_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'monster_id' => 'Monster ID',
            'item_id' => 'Item ID',
            'drop_rate' => 'Drop Rate',
            'meta' => 'Meta',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(\common\models\Item::className(), ['item_id' => 'item_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMonster()
    {
        return $this->hasOne(\common\models\Monster::className(), ['monster_id' => 'monster_id']);
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\MonsterItemQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\MonsterItemQuery(get_called_class());
    }


}
