<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "notification_log".
 *
 * @property integer $id
 * @property integer $status
 * @property integer $is_read
 * @property integer $type
 * @property string $from_address
 * @property string $reply_to_address
 * @property string $to_address
 * @property string $cc_address
 * @property string $bcc_address
 * @property string $subject
 * @property string $body
 * @property string $read_at
 * @property integer $read_count
 * @property string $scheduled_at
 * @property string $created_at
 * @property string $aliasModel
 */
abstract class NotificationLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'notification_log';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'updatedAtAttribute' => false,
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['status', 'is_read', 'type', 'read_count'], 'integer'],
            [['type', 'from_address', 'to_address', 'subject'], 'required'],
            [['from_address', 'reply_to_address', 'to_address', 'cc_address', 'bcc_address', 'subject', 'body'], 'string'],
            [['read_at', 'scheduled_at'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'status' => 'Status',
            'is_read' => 'Is Read',
            'type' => 'Type',
            'from_address' => 'From Address',
            'reply_to_address' => 'Reply To Address',
            'to_address' => 'To Address',
            'cc_address' => 'Cc Address',
            'bcc_address' => 'Bcc Address',
            'subject' => 'Subject',
            'body' => 'Body',
            'read_at' => 'Read At',
            'read_count' => 'Read Count',
            'created_at' => 'Created At',
            'scheduled_at' => 'Scheduled At',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\NotificationLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\NotificationLogQuery(get_called_class());
    }


}
