<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "onlinerecords".
 *
 * @property string $charname
 * @property string $charid
 * @property string $login_time
 * @property string $logout_time
 * @property string $online_time
 * @property integer $used
 * @property string $aliasModel
 */
abstract class Onlinerecords extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'onlinerecords';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['charname', 'charid', 'login_time', 'logout_time', 'online_time'], 'string'],
            [['used'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'charname' => 'Charname',
            'charid' => 'Charid',
            'login_time' => 'Login Time',
            'logout_time' => 'Logout Time',
            'online_time' => 'Online Time',
            'used' => 'Used',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\OnlinerecordsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\OnlinerecordsQuery(get_called_class());
    }


}
