<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "playerpkinfo".
 *
 * @property string $id
 * @property string $pker
 * @property string $pker_rb
 * @property string $pker_lvl
 * @property string $pked
 * @property string $pked_rb
 * @property string $pked_lvl
 * @property string $loc
 * @property string $time
 * @property string $pker_nation
 * @property string $pked_nation
 * @property string $aliasModel
 */
abstract class Playerpkinfo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'playerpkinfo';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pker', 'pker_rb', 'pker_lvl', 'pked', 'pked_rb', 'pked_lvl', 'loc', 'time', 'pker_nation', 'pked_nation'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'pker' => Yii::t('models', 'Pker'),
            'pker_rb' => Yii::t('models', 'Pker Rb'),
            'pker_lvl' => Yii::t('models', 'Pker Lvl'),
            'pked' => Yii::t('models', 'Pked'),
            'pked_rb' => Yii::t('models', 'Pked Rb'),
            'pked_lvl' => Yii::t('models', 'Pked Lvl'),
            'loc' => Yii::t('models', 'Loc'),
            'time' => Yii::t('models', 'Time'),
            'pker_nation' => Yii::t('models', 'Pker Nation'),
            'pked_nation' => Yii::t('models', 'Pked Nation'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\PlayerpkinfoQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\PlayerpkinfoQuery(get_called_class());
    }


}
