<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "RandChar".
 *
 * @property integer $RandNo
 * @property integer $Rand
 * @property string $AccountID
 * @property string $aliasModel
 */
abstract class RandChar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'RandChar';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['RandNo', 'AccountID'], 'required'],
            [['RandNo', 'Rand'], 'integer'],
            [['AccountID'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'RandNo' => Yii::t('models', 'Rand No'),
            'Rand' => Yii::t('models', 'Rand'),
            'AccountID' => Yii::t('models', 'Account ID'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\RandCharQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\RandCharQuery(get_called_class());
    }


}
