<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "Rebirth".
 *
 * @property string $c_id
 * @property integer $rebirth
 * @property string $update
 * @property string $account
 * @property string $gift1
 * @property string $gift2
 * @property string $gift3
 * @property string $gift4
 * @property string $aliasModel
 */
abstract class Rebirth extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Rebirth';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['c_id', 'rebirth', 'account'], 'required'],
            [['c_id', 'update', 'account', 'gift1', 'gift2', 'gift3', 'gift4'], 'string'],
            [['rebirth'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'c_id' => Yii::t('models', 'C ID'),
            'rebirth' => Yii::t('models', 'Rebirth'),
            'update' => Yii::t('models', 'Update'),
            'account' => Yii::t('models', 'Account'),
            'gift1' => Yii::t('models', 'Gift1'),
            'gift2' => Yii::t('models', 'Gift2'),
            'gift3' => Yii::t('models', 'Gift3'),
            'gift4' => Yii::t('models', 'Gift4'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\RebirthQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\RebirthQuery(get_called_class());
    }


}
