<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "referral".
 *
 * @property string $character_name
 * @property string $account_referred
 * @property integer $gift_taken
 * @property string $aliasModel
 */
abstract class Referral extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'referral';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['character_name', 'account_referred'], 'required'],
            [['character_name', 'account_referred'], 'string'],
            [['gift_taken'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'character_name' => 'Character Name',
            'account_referred' => 'Account Referred',
            'gift_taken' => 'Gift Taken',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ReferralQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ReferralQuery(get_called_class());
    }


}
