<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ReservedChar".
 *
 * @property string $AccountID
 * @property string $CharName
 * @property integer $ServerIdx
 * @property integer $CharClass
 * @property integer $Nation
 * @property integer $GroupSeatID
 * @property string $RegistDate
 * @property integer $Sex
 * @property string $Name
 * @property string $aliasModel
 */
abstract class ReservedChar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ReservedChar';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'CharName', 'ServerIdx', 'CharClass', 'Nation', 'RegistDate', 'Sex', 'Name'], 'required'],
            [['AccountID', 'CharName', 'Name'], 'string'],
            [['ServerIdx', 'CharClass', 'Nation', 'GroupSeatID', 'Sex'], 'integer'],
            [['RegistDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => 'Account ID',
            'CharName' => 'Char Name',
            'ServerIdx' => 'Server Idx',
            'CharClass' => 'Char Class',
            'Nation' => 'Nation',
            'GroupSeatID' => 'Group Seat ID',
            'RegistDate' => 'Regist Date',
            'Sex' => 'Sex',
            'Name' => 'Name',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ReservedCharQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ReservedCharQuery(get_called_class());
    }


}
