<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ReservedPresent".
 *
 * @property string $AccountID
 * @property string $SeatName
 * @property string $PresentType
 * @property string $Present
 * @property string $aliasModel
 */
abstract class ReservedPresent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ReservedPresent';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'PresentType', 'Present'], 'required'],
            [['AccountID', 'SeatName', 'PresentType', 'Present'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => 'Account ID',
            'SeatName' => 'Seat Name',
            'PresentType' => 'Present Type',
            'Present' => 'Present',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ReservedPresentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ReservedPresentQuery(get_called_class());
    }


}
