<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ReservedChar".
 *
 * @property string $AccountID
 * @property string $CharName
 * @property integer $ServerIdx
 * @property integer $CharClass
 * @property integer $Nation
 * @property integer $GroupSeatID
 * @property string $RegistDate
 * @property integer $Sex
 * @property string $Name
 * @property string $aliasModel
 */
abstract class ReservedChar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ReservedChar';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'CharName', 'ServerIdx', 'CharClass', 'Nation', 'RegistDate', 'Sex', 'Name'], 'required'],
            [['AccountID', 'CharName', 'Name'], 'string'],
            [['ServerIdx', 'CharClass', 'Nation', 'GroupSeatID', 'Sex'], 'integer'],
            [['RegistDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => Yii::t('models', 'Account ID'),
            'CharName' => Yii::t('models', 'Char Name'),
            'ServerIdx' => Yii::t('models', 'Server Idx'),
            'CharClass' => Yii::t('models', 'Char Class'),
            'Nation' => Yii::t('models', 'Nation'),
            'GroupSeatID' => Yii::t('models', 'Group Seat ID'),
            'RegistDate' => Yii::t('models', 'Regist Date'),
            'Sex' => Yii::t('models', 'Sex'),
            'Name' => Yii::t('models', 'Name'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ReservedCharQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ReservedCharQuery(get_called_class());
    }


}
