<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "RestoreRequest".
 *
 * @property integer $RestoreRequestID
 * @property string $AccountID
 * @property string $SCN
 * @property string $Result
 * @property string $RequestDate
 * @property string $ResultDate
 * @property string $aliasModel
 */
abstract class RestoreRequest extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'RestoreRequest';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['RestoreRequestID', 'AccountID', 'SCN', 'Result', 'RequestDate'], 'required'],
            [['RestoreRequestID'], 'integer'],
            [['AccountID', 'SCN', 'Result'], 'string'],
            [['RequestDate', 'ResultDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'RestoreRequestID' => 'Restore Request ID',
            'AccountID' => 'Account ID',
            'SCN' => 'Scn',
            'Result' => 'Result',
            'RequestDate' => 'Request Date',
            'ResultDate' => 'Result Date',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\RestoreRequestQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\RestoreRequestQuery(get_called_class());
    }


}
