<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "Sheet1".
 *
 * @property string $F1
 * @property string $aliasModel
 */
abstract class Sheet1 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Sheet1';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['F1'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'F1' => Yii::t('models', 'F1'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\Sheet1Query the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\Sheet1Query(get_called_class());
    }


}
