<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "shopping_cart".
 *
 * @property string $char_name
 * @property string $item_ids
 * @property string $credits_required
 * @property string $coupon_code
 * @property string $discount
 * @property integer $discount_allowed
 * @property integer $special_count
 * @property string $aliasModel
 */
abstract class ShoppingCart extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'shopping_cart';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['char_name', 'item_ids', 'credits_required'], 'required'],
            [['char_name', 'item_ids', 'coupon_code'], 'string'],
            [['credits_required', 'discount', 'discount_allowed', 'special_count'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'char_name' => Yii::t('models', 'Char Name'),
            'item_ids' => Yii::t('models', 'Item Ids'),
            'credits_required' => Yii::t('models', 'Credits Required'),
            'coupon_code' => Yii::t('models', 'Coupon Code'),
            'discount' => Yii::t('models', 'Discount'),
            'discount_allowed' => Yii::t('models', 'Discount Allowed'),
            'special_count' => Yii::t('models', 'Special Count'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ShoppingCartQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ShoppingCartQuery(get_called_class());
    }


}
