<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "sysdiagrams".
 *
 * @property string $name
 * @property integer $principal_id
 * @property integer $diagram_id
 * @property integer $version
 * @property resource $definition
 * @property string $aliasModel
 */
abstract class Sysdiagrams extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sysdiagrams';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'principal_id'], 'required'],
            [['name', 'definition'], 'string'],
            [['principal_id', 'version'], 'integer'],
            [['name', 'principal_id'], 'unique', 'targetAttribute' => ['name', 'principal_id'], 'message' => 'The combination of Name and Principal ID has already been taken.']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'name' => 'Name',
            'principal_id' => 'Principal ID',
            'diagram_id' => 'Diagram ID',
            'version' => 'Version',
            'definition' => 'Definition',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\SysdiagramsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\SysdiagramsQuery(get_called_class());
    }


}
