<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "UpdateLog".
 *
 * @property integer $UpdateLogID
 * @property string $ManageID
 * @property string $AccountID
 * @property string $UpdateContent
 * @property string $LogDate
 * @property string $aliasModel
 */
abstract class UpdateLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'UpdateLog';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['UpdateLogID', 'ManageID', 'AccountID', 'UpdateContent', 'LogDate'], 'required'],
            [['UpdateLogID'], 'integer'],
            [['ManageID', 'AccountID', 'UpdateContent'], 'string'],
            [['LogDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'UpdateLogID' => 'Update Log ID',
            'ManageID' => 'Manage ID',
            'AccountID' => 'Account ID',
            'UpdateContent' => 'Update Content',
            'LogDate' => 'Log Date',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\UpdateLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\UpdateLogQuery(get_called_class());
    }


}
