<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vAdultAge".
 *
 * @property integer $age
 * @property string $aliasModel
 */
abstract class VAdultAge extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vAdultAge';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['age'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'age' => 'Age',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\VAdultAgeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\VAdultAgeQuery(get_called_class());
    }


}
