<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vItemStorage".
 *
 * @property string $c_id
 * @property string $c_sheadera
 * @property string $c_sheaderb
 * @property string $c_sheaderc
 * @property string $c_headera
 * @property string $c_headerb
 * @property string $c_headerc
 * @property string $d_cdate
 * @property string $d_udate
 * @property string $c_status
 * @property string $m_body
 * @property string $aliasModel
 */
abstract class VItemStorage extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vItemStorage';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['c_id', 'c_sheadera', 'c_sheaderb', 'c_sheaderc', 'c_headera', 'c_headerb', 'c_headerc', 'c_status', 'm_body'], 'string'],
            [['d_cdate', 'd_udate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'c_id' => Yii::t('models', 'C ID'),
            'c_sheadera' => Yii::t('models', 'C Sheadera'),
            'c_sheaderb' => Yii::t('models', 'C Sheaderb'),
            'c_sheaderc' => Yii::t('models', 'C Sheaderc'),
            'c_headera' => Yii::t('models', 'C Headera'),
            'c_headerb' => Yii::t('models', 'C Headerb'),
            'c_headerc' => Yii::t('models', 'C Headerc'),
            'd_cdate' => Yii::t('models', 'D Cdate'),
            'd_udate' => Yii::t('models', 'D Udate'),
            'c_status' => Yii::t('models', 'C Status'),
            'm_body' => Yii::t('models', 'M Body'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\VItemStorageQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\VItemStorageQuery(get_called_class());
    }


}
