<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vStatAuth2".
 *
 * @property string $Result
 * @property integer $AuthTypeB
 * @property integer $AuthTypeC
 * @property integer $AuthTypeD
 * @property integer $AuthTypeE
 * @property integer $Total
 * @property string $ResultName
 * @property string $AuthTypeBP
 * @property string $AuthTypeCP
 * @property string $AuthTypeDP
 * @property string $AuthTypeEP
 * @property string $aliasModel
 */
abstract class VStatAuth2 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vStatAuth2';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Result', 'ResultName'], 'string'],
            [['AuthTypeB', 'AuthTypeC', 'AuthTypeD', 'AuthTypeE', 'Total', 'ResultName'], 'required'],
            [['AuthTypeB', 'AuthTypeC', 'AuthTypeD', 'AuthTypeE', 'Total'], 'integer'],
            [['AuthTypeBP', 'AuthTypeCP', 'AuthTypeDP', 'AuthTypeEP'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'Result' => 'Result',
            'AuthTypeB' => 'Auth Type B',
            'AuthTypeC' => 'Auth Type C',
            'AuthTypeD' => 'Auth Type D',
            'AuthTypeE' => 'Auth Type E',
            'Total' => 'Total',
            'ResultName' => 'Result Name',
            'AuthTypeBP' => 'Auth Type Bp',
            'AuthTypeCP' => 'Auth Type Cp',
            'AuthTypeDP' => 'Auth Type Dp',
            'AuthTypeEP' => 'Auth Type Ep',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\VStatAuth2Query the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\VStatAuth2Query(get_called_class());
    }


}
