<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "vStatAuth1".
 *
 * @property string $AuthType
 * @property integer $ResultO
 * @property integer $ResultA
 * @property integer $Total
 * @property string $AuthTypeName
 * @property string $ResultOP
 * @property string $ResultAP
 * @property string $aliasModel
 */
abstract class VStatAuth1 extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'vStatAuth1';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AuthType', 'AuthTypeName'], 'string'],
            [['ResultO', 'ResultA', 'Total', 'AuthTypeName'], 'required'],
            [['ResultO', 'ResultA', 'Total'], 'integer'],
            [['ResultOP', 'ResultAP'], 'number']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AuthType' => Yii::t('models', 'Auth Type'),
            'ResultO' => Yii::t('models', 'Result O'),
            'ResultA' => Yii::t('models', 'Result A'),
            'Total' => Yii::t('models', 'Total'),
            'AuthTypeName' => Yii::t('models', 'Auth Type Name'),
            'ResultOP' => Yii::t('models', 'Result Op'),
            'ResultAP' => Yii::t('models', 'Result Ap'),
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\VStatAuth1Query the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\VStatAuth1Query(get_called_class());
    }


}
