<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "WebLoginRecentLog".
 *
 * @property string $AccountID
 * @property string $LoginIP
 * @property integer $CntLoginFailure
 * @property string $CheckDate
 * @property string $AccessDenyDate
 * @property string $aliasModel
 */
abstract class WebLoginRecentLog extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'WebLoginRecentLog';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['AccountID', 'LoginIP', 'CntLoginFailure', 'CheckDate'], 'required'],
            [['AccountID', 'LoginIP'], 'string'],
            [['CntLoginFailure'], 'integer'],
            [['CheckDate', 'AccessDenyDate'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'AccountID' => 'Account ID',
            'LoginIP' => 'Login Ip',
            'CntLoginFailure' => 'Cnt Login Failure',
            'CheckDate' => 'Check Date',
            'AccessDenyDate' => 'Access Deny Date',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\WebLoginRecentLogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\WebLoginRecentLogQuery(get_called_class());
    }


}
