<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "ZipCode".
 *
 * @property integer $zipidx
 * @property string $zipcode
 * @property string $sido
 * @property string $gugun
 * @property string $dong
 * @property string $note1
 * @property string $note2
 * @property string $aliasModel
 */
abstract class ZipCode extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'ZipCode';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['zipidx', 'zipcode', 'sido', 'gugun', 'dong'], 'required'],
            [['zipidx'], 'integer'],
            [['zipcode', 'sido', 'gugun', 'dong', 'note1', 'note2'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'zipidx' => 'Zipidx',
            'zipcode' => 'Zipcode',
            'sido' => 'Sido',
            'gugun' => 'Gugun',
            'dong' => 'Dong',
            'note1' => 'Note1',
            'note2' => 'Note2',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \common\models\query\ZipCodeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\ZipCodeQuery(get_called_class());
    }


}
